### ISSUE TITLE
[SEM - 038]: Crear componente de botón 'No', 'SI' con variaciones

### ISSUE THREAD

**Issue by Ditmar** [Ditmar/backoffice-openscience#45]
**Descripción** Desarrollar un componente de botón 'No' siguiendo los principios de Atomic Design. Este componente será tratado como un átomo y deberá incluir todas sus variaciones visuales según la guía de estilo proporcionada.

**Detalles:**

Categoría: Atomo
**Variaciones:**
Color de fondo rojo (#ff4d4d) para estado normal.
Sombra y efecto de hover.
Variaciones para estados activo y desactivado.
Añadir efecto de transición para interacciones.
![image](https://github.com/user-attachments/assets/48fb4070-987d-4f69-97dc-dd4b3d540653)
Requerimientos de testing:

Implementar pruebas utilizando vitest  para verificar todos los estados del botón (activo, inactivo, hover).
**Documentación:**

Documentar cada variación del botón en Storybook.
Incluir notas sobre accesibilidad y uso recomendado del botón.
**Tareas:**

Diseñar el componente en Figma y obtener aprobación del equipo de diseño.
Implementar el componente en el código.
Escribir casos de prueba para el componente.
Documentar el componente en Storybook.
Revisión por pares y merge al repositorio principal.
**Variantes de color.**
![image](https://github.com/user-attachments/assets/8da95de4-af1c-4b1a-aa5b-7193b363d45a)

[figma](https://www.figma.com/design/XExR3sHnb2dcW5FYpYkt7y/Untitled?node-id=0-1&m=dev)

**Comment by Beymar-Cejas** [comment]
https://github.com/Ditmar/backoffice-openscience/tree/feature/SEM-038/src/ui/components/atoms/ButtonYesNo
